### ISSUE TITLE
Fix wrong API term on two pages

### ISSUE THREAD

**Issue by floriankraemer** [spryker/spryker-docs#1119]
These two pages use "Backend API" when it actually should say "Zed API" because they are still using the old API. Only modules that use the new backend API should use "Backend API" in the documentation.

* https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202204.0/backend-api-for-merchant-relationships-integration-guide.html
* https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202204.0/backend-api-for-merchant-relationships-integration-guide.html

**Comment by dereuromark** [comment]
@spryker/docs Has this been overlooked maybe?

**Comment by floriankraemer** [comment]
@dereuromark check the pages, its already fixed.
