### ISSUE TITLE
Image in Bundle Docs

### ISSUE THREAD

**Issue by patrickjaja** [spryker/spryker-docs#600]
https://docs.spryker.com/docs/scos/user/features/202108.0/product-bundles-feature-overview.html#product-bundle-entity-relationship-diagram

inside diagram the top left box has to be table "spy_product" + "id_product". Its a big difference, because we can only bundle concrete products not abstract.

**Comment by lenadoc** [comment]
Hi @patrickjaja!

Thank you very much for pointing this out! This issue has been fixed now.

Best regards,
The Spryker Docs team
