### ISSUE TITLE
Include an alternative download link for Docker (Apple Chip - ARM64)

### ISSUE THREAD

**Issue by wdstephen-spryker** [spryker/spryker-docs#882]
See point 1 [here](https://github.com/spryker/spryker-docs/blob/master/docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md#installing-and-configuring-required-software).

**Comment by lenadoc** [comment]
Hi @wdstephen-spryker!

Thank you very much for raising this issue! We have updated the installation link now. The change will appear on the docs website the next few hours.

Best regards,
The Spryker Docs team
