### ISSUE TITLE
Add temporary Apple M1 docker fix

### ISSUE THREAD

**Issue by wdstephen-spryker** [spryker/spryker-docs#883]
On this page:
https://github.com/spryker/spryker-docs/blob/master/docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md

Please add this alternative for those who have Apple M1 chips: 
```
git clone https://github.com/spryker/docker-sdk.git --branch apple-m1-adjustments --single-branch docker
```

**Comment by andriitserkovnyi** [comment]
The issue got self-resolved, thanks.
