### ISSUE TITLE
Missing CMS page navigation and broken links

### ISSUE THREAD

**Issue by markwallman** [spryker/spryker-docs#956]
The bottom of this page: https://docs.spryker.com/docs/scos/user/features/202204.0/cms-feature-overview/cms-feature-overview.html#cms-glossary
Has a number of links that are incorrect and link to checkout sections.
![Screenshot 2022-05-24 at 21 12 31](https://user-images.githubusercontent.com/1089655/170123792-93e565ca-4d32-4a9d-a54a-021bae1cb12d.png)

On further inspection, within the sidebar navigation there are a number of missing links that show as broken in the nav. I believe these are the pages that the above should be linking to.
![Screenshot 2022-05-24 at 21 12 01](https://user-images.githubusercontent.com/1089655/170123654-40a426cf-8c23-4f89-8926-f73108e408ce.png)

**Comment by lenadoc** [comment]
Hi @markwallman!

Thank you very much for raising this issue! It has now been fixed and will appear on the docs portal within a few hours.

Best regards,
The Spryker Docs team
